### ISSUE TITLE
Selecting the same char causes a problem.

### ISSUE THREAD

**Issue by NathanBruggeman** [axelvanherle/ticTacToeInCPP_task1#3]
Ik run het progamma met QT Creator 6.3.2 met de MinGW 11.2.0 64-bit  for C++ compiler.

Ik startte een game, selecteerde voor speler1 "Human", gaf mijn naam in en moest ten slotte een char ingeven waarmee ik wil spelen. Ik gaf voor deze char de letter "z" in. Als 2de speler kies ik nog eens "Human" en gaf weer een naam in. Nu koos ik voor speler2 dezelfde char om mee te spelen. Beide spelers hebben nu het character "z" geslecteerd. De game game runt nu. 

Het programma ziet de char "z" die speler1 heeft ingezet als dezelfde char van speler2 en visa versa. Je wint het spel als je 3 keer op een rij dezelfde char hebt staan. Doordat beide spelers dezelfde char hebben gaat het spel een winnaar aangeven als er 3keer dezelfde char staat, ookal staan er 3 op een rij waarvan er 2 chars van speler1 zijn en 1 char van speler2. De speler die de 3de char op een rij kan zetten wordt aangeven als da winnaar. Dit zou niet mogen omdat het 2 afzonderlijke spelers zijn en de chars van speler1 niet zouden mogen tellen voor speler2 en andersom. Dezelfde speler zou 3keer zijn char op een rij moeten hebben die hijzelf geplaatst heeft.

Dit kan opgelost worden door de ingegeven char van speler2 te checken op een gelijkenis met de char van speler1. Wanneer deze hetzelfde zouden zijn moet het programma dit aangeven, zeggen dat dit niet kan en vragen om een andere char in te geven welke speler1 niet gerbuikt.

![image](https://user-images.githubusercontent.com/101107621/207571061-aea3405b-8df3-4d38-a721-a64dcb2d6bb4.png)

![image](https://user-images.githubusercontent.com/101107621/207570896-4512cdb1-b5c3-4da6-8792-0a7a9b199030.png)

**Comment by axelvanherle** [comment]
Merged your pull request, consider this closed.
