### ISSUE TITLE
Program is unable to handle string input when choosing human or AI.

### ISSUE THREAD

**Issue by BrentGG** [axelvanherle/ticTacToeInCPP_task1#7]
**Describe the bug**
When choosing between a human or AI player, if the user inputs one or more non-numerical characters the program becomes unresponsive.

**To Reproduce**
1. Run the game.
2. Type one or more non-numerical characters.

**Expected behavior**
The program should handle the unexpected input and either ask for the input again, or continue otherwise.

**Actual behavior**
The program becomes unresponsive and seems to be in a loop of clearing and printing on the console.

**Comment by axelvanherle** [comment]
Merged your PR, consider this ticket closed
